config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users

    root to: "users#index"
  end

  root to: 'visitor#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :user
  resources :rfid_tags
  resources :lendings
  resources :detections
  resources :sensors

end

app/models/detection.rb
 class Detection < ActiveRecord::Base
	belongs_to :sensor
	belongs_to :rfid_tag
end

app/controllers/detections_controller.rb
class DetectionsController < ApplicationController
  before_action :set_detection, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin
  before_action :authenticate_user!


    def authenticate_admin
      redirect_to '/', alert: 'Not authorized.' unless current_user && current_user.admin?
    end

  # GET /detections
  # GET /detections.json
  def index
    @detections = Detection.all
  end

  # GET /detections/1
  # GET /detections/1.json
  def show
  end

  # GET /detections/new
  def new
    @detection = Detection.new
  end

  # GET /detections/1/edit
  def edit
  end

  # POST /detections
  # POST /detections.json
  def create
    @detection = Detection.new(detection_params)

    respond_to do |format|
      if @detection.save
        format.html { redirect_to @detection, notice: 'Detection was successfully created.' }
        format.json { render :show, status: :created, location: @detection }
      else
        format.html { render :new }
        format.json { render json: @detection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detections/1
  # PATCH/PUT /detections/1.json
  def update
    respond_to do |format|
      if @detection.update(detection_params)
        format.html { redirect_to @detection, notice: 'Detection was successfully updated.' }
        format.json { render :show, status: :ok, location: @detection }
      else
        format.html { render :edit }
        format.json { render json: @detection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detections/1
  # DELETE /detections/1.json
  def destroy
    @detection.destroy
    respond_to do |format|
      format.html { redirect_to detections_url, notice: 'Detection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detection
      @detection = Detection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detection_params
      params.require(:detection).permit(:tag_id, :sensor_id, :time)
    end
end

app/helpers/detections_helper.rb
module DetectionsHelper
end

app/views/detections/_form.html.erb
<%= form_for(@detection) do |f| %>
  <% if @detection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detection.errors.count, "error") %> prohibited this detection from being saved:</h2>

      <ul>
      <% @detection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.select :tag_id, options_from_collection_for_select(RfidTag.all, :tag_id, :tag_id) %>
  </div>
  
  <div class="field">
    <%= f.label :sensor_id %><br>
    <%= f.select :sensor_id, options_from_collection_for_select(Sensor.all, :sensor_id, :sensor_id) %>
  </div>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/detections/edit.html.erb
<h1>Editing Detection</h1>

<%= render 'form' %>

<%= link_to 'Show', @detection %> |
<%= link_to 'Back', detections_path %>

app/views/detections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Detections</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Sensor</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @detections.each do |detection| %>
      <tr>
        <td><%= detection.tag_id %></td>
        <td><%= detection.sensor_id %></td>
        <td><%= detection.time %></td>
        <td><%= link_to 'Show', detection %></td>
        <td><%= link_to 'Edit', edit_detection_path(detection) %></td>
        <td><%= link_to 'Destroy', detection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detection', new_detection_path %>

app/views/detections/new.html.erb
<h1>New Detection</h1>

<%= render 'form' %>

<%= link_to 'Back', detections_path %>

app/views/detections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @detection.tag_id %>
</p>

<p>
  <strong>Sensor:</strong>
  <%= @detection.sensor_id %>
</p>

<p>
  <strong>Time:</strong>
  <%= @detection.time %>
</p>

<%= link_to 'Edit', edit_detection_path(@detection) %> |
<%= link_to 'Back', detections_path %>