config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users

    root to: "users#index"
  end

  root to: 'visitor#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :user
  resources :rfid_tags
  resources :lendings
  resources :detections
  resources :sensors

end

app/models/rfid_tag.rb
class RfidTag < ActiveRecord::Base
	has_many :detections
	has_many :sensors, :through => :lendings
	has_many :users, :through => :lendings
end

app/controllers/rfid_tags_controller.rb
class RfidTagsController < ApplicationController
  before_action :set_rfid_tag, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin
  before_action :authenticate_user!


    def authenticate_admin
      redirect_to '/', alert: 'Not authorized.' unless current_user && current_user.admin?
    end

  # GET /rfid_tags
  # GET /rfid_tags.json
  def index
    @rfid_tags = RfidTag.all
  end

  # GET /rfid_tags/1
  # GET /rfid_tags/1.json
  def show
  end

  # GET /rfid_tags/new
  def new
    @rfid_tag = RfidTag.new
  end

  # GET /rfid_tags/1/edit
  def edit
  end

  # POST /rfid_tags
  # POST /rfid_tags.json
  def create
    @rfid_tag = RfidTag.new(rfid_tag_params)

    respond_to do |format|
      if @rfid_tag.save
        format.html { redirect_to @rfid_tag, notice: 'Rfid tag was successfully created.' }
        format.json { render :show, status: :created, location: @rfid_tag }
      else
        format.html { render :new }
        format.json { render json: @rfid_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rfid_tags/1
  # PATCH/PUT /rfid_tags/1.json
  def update
    respond_to do |format|
      if @rfid_tag.update(rfid_tag_params)
        format.html { redirect_to @rfid_tag, notice: 'Rfid tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @rfid_tag }
      else
        format.html { render :edit }
        format.json { render json: @rfid_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rfid_tags/1
  # DELETE /rfid_tags/1.json
  def destroy
    @rfid_tag.destroy
    respond_to do |format|
      format.html { redirect_to rfid_tags_url, notice: 'Rfid tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rfid_tag
      @rfid_tag = RfidTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rfid_tag_params
      params.require(:rfid_tag).permit(:tag_id)
    end
end

app/helpers/rfid_tags_helper.rb
module RfidTagsHelper
end

app/views/rfid_tags/_form.html.erb
<%= form_for(@rfid_tag) do |f| %>
  <% if @rfid_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rfid_tag.errors.count, "error") %> prohibited this rfid_tag from being saved:</h2>

      <ul>
      <% @rfid_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.number_field :tag_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rfid_tags/edit.html.erb
<h1>Editing Rfid Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @rfid_tag %> |
<%= link_to 'Back', rfid_tags_path %>

app/views/rfid_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rfid Tags</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rfid_tags.each do |rfid_tag| %>
      <tr>
        <td><%= rfid_tag.tag_id %></td>
        <td><%= link_to 'Show', rfid_tag %></td>
        <td><%= link_to 'Edit', edit_rfid_tag_path(rfid_tag) %></td>
        <td><%= link_to 'Destroy', rfid_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rfid tag', new_rfid_tag_path %>

app/views/rfid_tags/new.html.erb
<h1>New Rfid Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', rfid_tags_path %>

app/views/rfid_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @rfid_tag.tag_id %>
</p>

<%= link_to 'Edit', edit_rfid_tag_path(@rfid_tag) %> |
<%= link_to 'Back', rfid_tags_path %>