config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users

    root to: "users#index"
  end

  root to: 'visitor#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :user
  resources :rfid_tags
  resources :lendings
  resources :detections
  resources :sensors

end

app/models/lending.rb
class Lending < ActiveRecord::Base
	belongs_to :rfid_tag
	belongs_to :user
end

app/controllers/lendings_controller.rb
class LendingsController < ApplicationController
  before_action :set_lending, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_admin
  before_action :authenticate_user!


    def authenticate_admin
      redirect_to '/', alert: 'Not authorized.' unless current_user && current_user.admin?
    end

  # GET /lendings
  # GET /lendings.json
  def index
    @lendings = Lending.all
  end

  # GET /lendings/1
  # GET /lendings/1.json
  def show
  end

  # GET /lendings/new
  def new
    @lending = Lending.new
  end

  # GET /lendings/1/edit
  def edit
  end

  # POST /lendings
  # POST /lendings.json
  def create
    @lending = Lending.new(lending_params)

    respond_to do |format|
      if @lending.save
        format.html { redirect_to @lending, notice: 'Lending was successfully created.' }
        format.json { render :show, status: :created, location: @lending }
      else
        format.html { render :new }
        format.json { render json: @lending.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lendings/1
  # PATCH/PUT /lendings/1.json
  def update
    respond_to do |format|
      if @lending.update(lending_params)
        format.html { redirect_to @lending, notice: 'Lending was successfully updated.' }
        format.json { render :show, status: :ok, location: @lending }
      else
        format.html { render :edit }
        format.json { render json: @lending.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lendings/1
  # DELETE /lendings/1.json
  def destroy
    @lending.destroy
    respond_to do |format|
      format.html { redirect_to lendings_url, notice: 'Lending was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lending
      @lending = Lending.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lending_params
      params.require(:lending).permit(:tag_id, :user_id, :from, :to)
    end
end

app/helpers/lendings_helper.rb
module LendingsHelper
end

app/views/lendings/_form.html.erb
<%= form_for(@lending) do |f| %>
  <% if @lending.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lending.errors.count, "error") %> prohibited this lending from being saved:</h2>

      <ul>
      <% @lending.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.select :tag_id, options_from_collection_for_select(RfidTag.all, :tag_id, :tag_id) %>
  </div>

 <div class="field">
    <%= f.label :user %><br>
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :from %><br>
    <%= f.datetime_select :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br>
    <%= f.datetime_select :to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/lendings/edit.html.erb
<h1>Editing Lending</h1>

<%= render 'form' %>

<%= link_to 'Show', @lending %> |
<%= link_to 'Back', lendings_path %>

app/views/lendings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lendings</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>User</th>
      <th>From</th>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lendings.each do |lending| %>
      <tr>
        <td><%= lending.tag_id %></td>
        <td><%= lending.user_id %></td>
        <td><%= lending.from %></td>
        <td><%= lending.to %></td>
        <td><%= link_to 'Show', lending %></td>
        <td><%= link_to 'Edit', edit_lending_path(lending) %></td>
        <td><%= link_to 'Destroy', lending, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lending', new_lending_path %>

app/views/lendings/new.html.erb
<h1>New Lending</h1>

<%= render 'form' %>

<%= link_to 'Back', lendings_path %>

app/views/lendings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @lending.tag_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @lending.user.name %>
</p>

<p>
  <strong>From:</strong>
  <%= @lending.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @lending.to %>
</p>

<%= link_to 'Edit', edit_lending_path(@lending) %> |
<%= link_to 'Back', lendings_path %>