config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users

    root to: "users#index"
  end

  root to: 'visitor#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :user
  resources :rfid_tags
  resources :lendings
  resources :detections
  resources :sensors

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
	has_many :detections
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin
  before_action :authenticate_user!


    def authenticate_admin
      redirect_to '/', alert: 'Not authorized.' unless current_user && current_user.admin?
    end

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:sensor_id, :date, :coordinate)
    end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sensor_id %><br>
    <%= f.text_field :sensor_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :coordinate %><br>
    <%= f.text_area :coordinate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sensors</h1>

<table>
  <thead>
    <tr>
      <th>Sensor</th>
      <th>Date</th>
      <th>Coordinate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.sensor_id %></td>
        <td><%= sensor.date %></td>
        <td><%= sensor.coordinate %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sensor:</strong>
  <%= @sensor.sensor_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sensor.date %>
</p>

<p>
  <strong>Coordinate:</strong>
  <%= @sensor.coordinate %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>